post_install() {
	echo "All sophisticated SIP packet handling is provided through dedicated 'opensips' modules."
	echo "Since version 3.0 OpenSIPS will be managed either via a python commandline tool 'opensips-cli'"
	echo "or via the web-frontend 'opensip-cp'. Both packages may be installed side by side."

	useradd --system --user-group \
		--shell /bin/false \
		--comment "OpenSIPS" opensips || true
}
